app.swagger:
    path: /app/api/v1/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
    path: /app/api/v1/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
