nelmio_api_doc:
    documentation:
        info:
            title: Simple Book Catalog
            description: Train
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/books/api/v1(?!/doc$) # Accepts routes under /api except /api/doc
